### ISSUE TITLE
Problem with spotify: xenforo 1

### ISSUE THREAD

**Issue by techinnov-974** [s9e/XenForoMediaBBCodes#11]
Hello, I install your addon on xenforo, when I use the tag [media = spotify] [/ media], example: [media = spotify] spotify: track: 4bz7uB4edifWKJXSDxwHcs [/ media] nothing comes out embed, the part "track: 4bz7uB4edifWKJXSDxwHcs" is not taken into account see screen http://prntscr.com/hq9tko

Can you fix this problem plz

**Comment by JoshyPHP** [comment]
How did you generate that markup?

`[media = spotify] spotify: track: 4bz7uB4edifWKJXSDxwHcs [/ media]`

**Comment by JoshyPHP** [comment]
Have you tried using the link from "Copier le lien vers la chanson" instead of the URI?

**Comment by techinnov-974** [comment]
When I use uri in add media it gives me an error: http://prntscr.com/hqjneu
The "Copy link to the song" works

I test this for uri it works
If that can help you

`spotify:track:{$id}`

`<iframe src="https://open.spotify.com/embed?uri={$id}" width="300" height="380" frameborder="0" allowtransparency="true"></iframe>`

**Comment by JoshyPHP** [comment]
XenForo's media sites are meant to work with URLs such as `https://open.spotify.com/track/1rWnJU3r2smr7gtGOq3jwa`, not URIs such as `spotify:track:1rWnJU3r2smr7gtGOq3jwa`. I don't think I will add support for URIs because it complicates a number of things and as long as it's possible to get a working URL (not URI) for a song then there's little added value in it.
