### ISSUE TITLE
Imgur not working in spoilers

### ISSUE THREAD

**Issue by Sir-Will** [s9e/XenForoMediaBBCodes#12]
After few recent updates the imgur embed does no longer work in spoilers for me:
![](https://i.imgur.com/jz0q82y.jpg)

**Comment by JoshyPHP** [comment]
If it works on its own but not inside of a spoiler tag then you should look into how the spoiler tag works. XenForo doesn't have a spoiler BBCode so I can't reproduce it locally.

**Comment by Xon** [comment]
XenForo does have a spoiler bbcode; [spoiler][/spoiler]

**Comment by JoshyPHP** [comment]
Does it? Ok, I didn't know about that. I'll take a look at it asap then.

**Comment by JoshyPHP** [comment]
Looked into it and it turns out Imgur doesn't load properly inside of a hidden element. There's nothing we can do about that apart from *not* loading it if it's inside a hidden element. I updated the lazy loader so that embeds inside of a spoiler don't get loaded. If you update to the latest version and turn on the "Defer loading" option, you should be able to load Imgur embeds within spoilers.

**Comment by Sir-Will** [comment]
Now it loads the embed but not the image with both defer enabled and disabled.
![](https://image.prntscr.com/image/WgDivJMPQ0i9hnc3o2dzoA.png)

**Comment by JoshyPHP** [comment]
No need to post a screenshot of an empty screen. Instead, provide all the details required to reproduce the same behaviour. For instance, what text needs to be entered to get that results.

**Comment by Sir-Will** [comment]
`[SPOILER][MEDIA=imgur]a/SPonn[/MEDIA][/SPOILER]`

**Comment by JoshyPHP** [comment]
This works fine on my board. Make sure you have the latest version of the add-on installed, clear your browser's cache and it may fix it for you.

**Comment by Sir-Will** [comment]
Oh, I'm using the BBM Spoiler not the vanilla one but not sure how to fix it without switching to the vanilla one.
