### ISSUE TITLE
Support for Bitchute.com, Minds.com and Gab.ai

### ISSUE THREAD

**Issue by lambschopping** [s9e/XenForoMediaBBCodes#13]
Would you please add support for Bitchute.com, Minds.com and Gab.ai?

Thanks for all your hard work on this project.

**Comment by JoshyPHP** [comment]
I'm not going to add any of them for the moment because I don't think they have reached a big enough audience yet but I'm keeping an eye on BitChute.com and will reevaluate later.

In addition, I don't think that BitChute currently officially supports embedding and Gab.ai does not seem to support embedding at all.

With that said, if you follow [XenForo's media sites tutorial](https://xenforo.com/help/bb-code-media-sites/) you should be able to manually create a media site for Minds on your installation.
